"""add github_username column to users

Revision ID: 9f2e7d1c5a9b
Revises: fb8e508f020d
Create Date: 2026-04-02 12:58:30.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2e7d1c5a9b'
down_revision: Union[str, Sequence[str], None] = 'fb8e508f020d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_github_username'), 'users', ['github_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_username'), table_name='users')
    op.drop_column('users', 'github_username')
    # ### end Alembic commands ###
